# Generated by Django 3.2.12 on 2022-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='qualtity_as_float',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
