# Generated by Django 3.2.12 on 2022-03-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_qualtity_as_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='qualtity_as_float',
            new_name='quantity_as_float',
        ),
    ]
